// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNl63a9xCTPa9RTcnZr7XuhxxaWHf-rgk',
    appId: '1:427394139285:android:965f83e9aec3c0dbec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsFIrA-0J6BuY7iVoFRYCDJQr4xUJpoYA',
    appId: '1:427394139285:web:9867b07f94e2984aec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    authDomain: 'akjol-f479a.firebaseapp.com',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    measurementId: 'G-CEFBF81WNR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VRtlitN06WcDlGzFg_RvqtickZiPkIE',
    appId: '1:427394139285:ios:3ef852d58c04d2caec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    iosBundleId: 'com.akjolui.courier',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VRtlitN06WcDlGzFg_RvqtickZiPkIE',
    appId: '1:427394139285:ios:3ef852d58c04d2caec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    iosBundleId: 'com.akjolui.courier',
  );

}
