// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNl63a9xCTPa9RTcnZr7XuhxxaWHf-rgk',
    appId: '1:427394139285:android:3a2945b037afac8bec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsFIrA-0J6BuY7iVoFRYCDJQr4xUJpoYA',
    appId: '1:427394139285:web:e11983e7379a6becec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    authDomain: 'akjol-f479a.firebaseapp.com',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    measurementId: 'G-J9EMNDGWJK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8VRtlitN06WcDlGzFg_RvqtickZiPkIE',
    appId: '1:427394139285:ios:f5019054c28f4032ec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    iosBundleId: 'com.takesep.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8VRtlitN06WcDlGzFg_RvqtickZiPkIE',
    appId: '1:427394139285:ios:f5019054c28f4032ec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    iosBundleId: 'com.takesep.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFIrA-0J6BuY7iVoFRYCDJQr4xUJpoYA',
    appId: '1:427394139285:web:999072ac9fc6d506ec079c',
    messagingSenderId: '427394139285',
    projectId: 'akjol-f479a',
    authDomain: 'akjol-f479a.firebaseapp.com',
    storageBucket: 'akjol-f479a.firebasestorage.app',
    measurementId: 'G-PRL6MN3PN6',
  );

}